import React from 'react'
import {Scene, Router, Actions} from 'react-native-router-flux'
import LoginForm from './components/LoginForm'
import EmployeeList from './components/EmployeeList'
import EmployeeCreate from './components/EmployeeCreate'
import EmployeeEdit from './components/EmployeeEdit'



/*
NAVIGATION WITH ROUTER FLUX

setting up navigation in react-native is similar to navigation in react.js.
we install react-native-router-flux just like we install react-router-dom in react.js
we create a seperate component for our routing just like this particular file.
we import Scene and Router from react-native-router-flux just like we import Router, Switch e.t.c in react.js
inside our routing component, we will have <Router> component wrapping other things(the Scenes).
we must have a parent Scene that will wrapp all the Scenes we will have in our app. the parent scene will also have its own key
Each Scene will have its own key, component, and title props. the title is optional likewise initial
The key is similar to path in react.js, the component props ia thesame as that of the react.js
The title allows the screen to have header with a title
The initial props denote that the Scene with the initial props should be the first screen that will be render upon opening the app

to start routing, in our root component(that is where we use the provider), we import anyname from '../router.js'  
we then use <anyname /> in our return (as a child to the provider) it will automatically render the component of the scene

So anywhere we want any of the component(scene) to be render, we import {Actions} from 'react-native-router-flux'
we will then call Actions.sceneKeyName()


we can style probably our header generated by routerflux(if we use title props) by using sceneStyle props on Router tag
the sceneStyle is used on the router and the styling applies to the scenes

hideNavBar is for disabling the header for the parent scene
*/


const Routes = () => {
    return (
        <Router sceneStyle={{paddingTop: 1}} titleStyle={{textAlign: 'center', flex: 1, color: "white"}} 
            navigationBarStyle={{backgroundColor: "#007aff"}}
        >
            <Scene key="root" hideNavBar>
                <Scene key="auth" initial>
                    <Scene key="login" component={LoginForm} title="LOGIN" />
                </Scene>
                <Scene key="main">
                    <Scene key="employeeList" 
                        rightTitle="Add"
                        rightButtonTextStyle={{color: "white", paddingRight: 10}}
                        onRight={() => {Actions.employeeCreate()}}
                        component={EmployeeList} 
                        title="Employees" 
                        initial
                    />
                    <Scene key="employeeCreate" 
                        component={EmployeeCreate} 
                        title="Create Employee" 
                        backButtonTextStyle = {{color:'white'}}
                        backButtonTintColor = 'white'
                    />

                    <Scene key="employeeEdit" 
                        component={EmployeeEdit} 
                        title="Edit Employee" 
                        backButtonTextStyle = {{color:'white'}}
                        backButtonTintColor = 'white'
                    />
                </Scene>
            </Scene>
            
        </Router>
    )
}

export default Routes